import pytest

from video_to_artifact_agent.schemas import ArtifactRequirement, BuildSpec, SourceInfo, SourceKind
from video_to_artifact_agent.transcripts import (
    TranscriptCoverageError,
    merge_transcript_evidence,
    parse_transcript,
)


def test_parse_srt_subtitle_evidence_derives_duration_coverage_and_language() -> None:
    transcript = parse_transcript(
        """1
00:00:00,000 --> 00:00:02,500
Build a revenue model.

2
00:00:02,500 --> 00:00:05,000
Use the assumptions on screen.
""",
        fmt="srt",
        kind="subtitle",
        language="en",
        audio_duration_sec=5,
    )

    assert transcript.kind == "subtitle"
    assert transcript.language == "en"
    assert transcript.audio_duration_sec == 5
    assert transcript.coverage_pct == 100.0
    assert [segment.text for segment in transcript.segments] == [
        "Build a revenue model.",
        "Use the assumptions on screen.",
    ]
    assert transcript.segments[0].start == 0
    assert transcript.segments[0].end == 2.5


def test_parse_webvtt_subtitle_evidence_ignores_header_and_notes() -> None:
    transcript = parse_transcript(
        """WEBVTT

NOTE generated by subtitle service

00:00:01.000 --> 00:00:03.000 align:start position:0%
First instruction.

00:00:03.000 --> 00:00:06.250
Second instruction.
""",
        fmt="vtt",
        kind="subtitle",
        audio_duration_sec=6.25,
    )

    assert transcript.coverage_pct == 100.0
    assert [(segment.start, segment.end, segment.text) for segment in transcript.segments] == [
        (1.0, 3.0, "First instruction."),
        (3.0, 6.25, "Second instruction."),
    ]


def test_parse_json_segments_as_asr_evidence() -> None:
    transcript = parse_transcript(
        """{
  "language": "zh",
  "duration": 12,
  "segments": [
    {"start": 0, "end": 5, "text": "打开仪表盘"},
    {"start_sec": 5, "end_sec": 12, "text": "导出报告"}
  ]
}""",
        fmt="json",
        kind="asr",
        model="fixture-asr",
    )

    assert transcript.kind == "asr"
    assert transcript.model == "fixture-asr"
    assert transcript.language == "zh"
    assert transcript.audio_duration_sec == 12
    assert transcript.coverage_pct == 100.0
    assert transcript.segments[1].text == "导出报告"


def test_coverage_gate_rejects_short_transcript_when_requested() -> None:
    with pytest.raises(TranscriptCoverageError, match="coverage"):
        parse_transcript(
            """1
00:00:00,000 --> 00:00:04,000
Too short.
""",
            fmt="srt",
            kind="subtitle",
            audio_duration_sec=10,
            coverage_threshold_pct=50,
            require_coverage=True,
        )


def test_merge_transcript_evidence_updates_build_spec_and_adds_l2_record() -> None:
    spec = BuildSpec(
        source=SourceInfo(kind=SourceKind.local_file, local_path="/tmp/demo.mp4"),
        artifact=ArtifactRequirement(artifact_type="excel", title="Demo"),
    )
    transcript = parse_transcript(
        """1
00:00:00,000 --> 00:00:10,000
Make an Excel workbook.
""",
        fmt="srt",
        kind="subtitle",
        audio_duration_sec=10,
    )

    updated = merge_transcript_evidence(spec, transcript, source_ref="https://example.com/demo.srt?token=secret")

    assert updated is spec
    assert spec.transcript == transcript
    assert spec.achieved_evidence_level == "L2"
    assert len(spec.evidence) == 1
    assert spec.evidence[0].kind == "subtitle"
    assert spec.evidence[0].level == "L2"
    assert spec.evidence[0].source_ref == "https://example.com/demo.srt?<redacted>"
    assert spec.evidence[0].metadata["coverage_pct"] == 100.0
